//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_AD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project_AD.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string addMemberButton {
            get {
                return ResourceManager.GetString("addMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string backButton {
            get {
                return ResourceManager.GetString("backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Prices.
        /// </summary>
        internal static string checkPricesButton {
            get {
                return ResourceManager.GetString("checkPricesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Prices.
        /// </summary>
        internal static string checkPricesLabel {
            get {
                return ResourceManager.GetString("checkPricesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string cityLabel {
            get {
                return ResourceManager.GetString("cityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exitButton {
            get {
                return ResourceManager.GetString("exitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string firstNameLabel {
            get {
                return ResourceManager.GetString("firstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Type.
        /// </summary>
        internal static string frequencyTypeGB {
            get {
                return ResourceManager.GetString("frequencyTypeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string languageButton {
            get {
                return ResourceManager.GetString("languageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lastNameLabel {
            get {
                return ResourceManager.GetString("lastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string loginEmployeeButton {
            get {
                return ResourceManager.GetString("loginEmployeeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string loginMemberButton {
            get {
                return ResourceManager.GetString("loginMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logoutButton {
            get {
                return ResourceManager.GetString("logoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Payment.
        /// </summary>
        internal static string makePaymentButton {
            get {
                return ResourceManager.GetString("makePaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Membership.
        /// </summary>
        internal static string manageMembershipButton {
            get {
                return ResourceManager.GetString("manageMembershipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID:.
        /// </summary>
        internal static string memberIdLabel {
            get {
                return ResourceManager.GetString("memberIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Type.
        /// </summary>
        internal static string membershipTypeGB {
            get {
                return ResourceManager.GetString("membershipTypeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Prices: .
        /// </summary>
        internal static string monthlyLabel {
            get {
                return ResourceManager.GetString("monthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string monthlyRB {
            get {
                return ResourceManager.GetString("monthlyRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string phoneNumberLabel {
            get {
                return ResourceManager.GetString("phoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium: 29.99$.
        /// </summary>
        internal static string premiumMonthlyLabel {
            get {
                return ResourceManager.GetString("premiumMonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        internal static string premiumRB {
            get {
                return ResourceManager.GetString("premiumRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium: 389.75$.
        /// </summary>
        internal static string premiumYearlyLabel {
            get {
                return ResourceManager.GetString("premiumYearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string previousButton {
            get {
                return ResourceManager.GetString("previousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Friday! Achieve your fitness goals with our best deals of the year. Join now and save big on memberships.
        /// </summary>
        internal static string promotionLabel {
            get {
                return ResourceManager.GetString("promotionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string provinceLabel {
            get {
                return ResourceManager.GetString("provinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular: 19.99$.
        /// </summary>
        internal static string regularMonthlyLabel {
            get {
                return ResourceManager.GetString("regularMonthlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string regularRB {
            get {
                return ResourceManager.GetString("regularRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular: 259.75$.
        /// </summary>
        internal static string regularYearlyLabel {
            get {
                return ResourceManager.GetString("regularYearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Member.
        /// </summary>
        internal static string removeMemberButton {
            get {
                return ResourceManager.GetString("removeMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string signupButton {
            get {
                return ResourceManager.GetString("signupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        internal static string streetNameLabel {
            get {
                return ResourceManager.GetString("streetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Number.
        /// </summary>
        internal static string streetNumberLabel {
            get {
                return ResourceManager.GetString("streetNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submitButton {
            get {
                return ResourceManager.GetString("submitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Member.
        /// </summary>
        internal static string updateMemberButton {
            get {
                return ResourceManager.GetString("updateMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateProfileButton {
            get {
                return ResourceManager.GetString("updateProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Member.
        /// </summary>
        internal static string viewMemberButton {
            get {
                return ResourceManager.GetString("viewMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Notifications.
        /// </summary>
        internal static string viewNotificationsButton {
            get {
                return ResourceManager.GetString("viewNotificationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string viewProfileButton {
            get {
                return ResourceManager.GetString("viewProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Prices:.
        /// </summary>
        internal static string yearlyLabel {
            get {
                return ResourceManager.GetString("yearlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string yearlyRB {
            get {
                return ResourceManager.GetString("yearlyRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string zipCodeLabel {
            get {
                return ResourceManager.GetString("zipCodeLabel", resourceCulture);
            }
        }
    }
}
